# Base image for smart contract testing with Foundry
FROM ghcr.io/foundry-rs/foundry:latest as foundry

# Official Python image
FROM python:3.11-slim

# Install required tools
RUN apt-get update && apt-get install -y \
    git \
    curl \
    just \
    && rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /app

# Install Poetry
RUN pip install --no-cache-dir poetry

# Copy Poetry files
COPY pyproject.toml poetry.lock* /app/

# Configure Poetry: disable virtualenv creation
RUN poetry config virtualenvs.create false

# Install dependencies (including dev for testing)
RUN poetry install --no-interaction --no-ansi

# Copy Foundry binaries to the bin directory
COPY --from=foundry /usr/local/bin/ /usr/local/bin/

# Download and place the cross-anvil binary in /usr/local/bin
RUN curl -L https://github.com/earth-mind/cross-anvil/releases/download/v0.0.5/cross-anvil_v0.0.5_linux_amd64.tar.gz -o cross-anvil.tar.gz \
    && tar -xzf cross-anvil.tar.gz -C /usr/local/bin/ \
    && rm cross-anvil.tar.gz \
    && chmod +x /usr/local/bin/cross-anvil*

# Clone the repository
RUN git clone https://github.com/earth-mind/contracts.git /app/contracts

ENV MNEMONIC="test test test test test test test test test test test junk"
ENV CHAIN1_URL="http://localhost:8555"
ENV CHAIN2_URL="http://localhost:8556"
ENV CHAIN1_ID="31337"
ENV CHAIN2_ID="31338"
ENV SENDER="0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

RUN just deploy_local_contracts

WORKDIR /app/contracts

RUN forge build

# Set work directory back to /app for Python tests
WORKDIR /app

# Copy the rest of the code into the container
COPY . /app

# Starting cross-anvil before running tests
CMD cross-anvil & poetry run pytest
