name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    # steps:
    # - uses: actions/checkout@v1
    # - name: Install tox
    #   run: pip install tox
    # - name: Run tox
    #   run: tox
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
      
# Reference https://stackoverflow.com/questions/59532176/how-to-run-tox-from-github-actions

# to think
# jobs:
#     build-and-push-app:
#       runs-on: ubuntu-latest
#       steps:
#       - uses: actions/checkout@v2
#       - name: Build app image
#         run: docker build -f Dockerfile.app -t myapp:latest .
  
#     test:
#       runs-on: ubuntu-latest
#       steps:
#       - uses: actions/checkout@v2
#       - name: Build test image
#         run: docker build -f Dockerfile.test -t myapp-test:latest .
#       - name: Run tests
#         run: docker run myapp-test
  