name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build . -f Dockerfile.test -t earthmind-test

    - name: Run tests
      run: docker run earthmind-test
  